### PR TITLE
OEL-1134: Add OE Contact forms honeypot

### PR DESCRIPTION
**Pull request by Maxfire**
### Description
Composer.json and showcase.info to enable contact form honeypot submodule.

### CODE REVIEW

**Comment by Maxfire** [comment]
Failing because it needs https://github.com/openeuropa/oe_contact_forms/pull/45 to be merged.

**Review by drishu — APPROVED** [review]

**Review by drishu — COMMENTED** [review]
Rename the PR title:
from "Oel 1134: Contact forms honeypot dependency added."
to "OEL-1134: Add OE Contact forms honeypot"

**Review by drishu — CHANGES_REQUESTED** [review]
we will need to handle the contact form changes in composer, lets use
```
"openeuropa/oe_contact_forms": "dev-OEL-1134",
```
till it is merged

**Review by drishu — DISMISSED** [review]

**Comment by ArthurC008** [comment]
HI there, 
I've swapped a token few days ago and won't let me sell and i was wondering can you guys help me or to the contract enable the swap so i can get my Eth back? if i can swap the token and get my eth back i will reward you guys with some eth too...thanks in advance.

**Review by brummbar — DISMISSED** [review]

**Review by drishu — APPROVED** [review]

**Review by brummbar — APPROVED** [review]

**Pull request merged**
